import fs from "node:fs/promises";
import crypto from "node:crypto";
import { ENV_FILE, STATE_FILE, ROOT } from "./paths.js";

function randomHex(bytes) {
  return crypto.randomBytes(bytes).toString("hex");
}

/**
 * Embedding profiles. Each maps to env vars consumed by the backend.
 * `kind: "local"` uses sentence-transformers; `kind: "api"` uses an HTTP
 * provider and requires an API key.
 *
 * All profiles are pinned to 768 dimensions to match the existing pgvector
 * schema. API providers truncate (Gemini outputDimensionality, OpenAI
 * dimensions param).
 */
export const EMBEDDING_PROFILES = {
  local_balanced: {
    label: "Local — sentence-transformers, jina-embeddings-v2-base-code (~440MB, no key)",
    kind: "local",
    available: true,
    env: {
      EMBEDDING_PROVIDER: "local",
      EMBEDDING_MODEL: "jinaai/jina-embeddings-v2-base-code",
      EMBEDDING_DIMENSION: "768",
      EMBEDDING_DEVICE: "auto",
      EMBEDDING_BATCH_SIZE: "64",
    },
  },
  gemini: {
    label: "Google Gemini — gemini-embedding-001",
    kind: "api",
    available: true,
    keyEnvVar: "GEMINI_API_KEY",
    keyHint: "https://aistudio.google.com/apikey",
    env: {
      EMBEDDING_PROVIDER: "gemini",
      EMBEDDING_MODEL: "gemini-embedding-001",
      EMBEDDING_DIMENSION: "768",
      EMBEDDING_BATCH_SIZE: "32",
    },
  },
  openai: {
    label: "OpenAI — text-embedding-3-small",
    kind: "api",
    available: true,
    keyEnvVar: "OPENAI_API_KEY",
    keyHint: "https://platform.openai.com/api-keys",
    env: {
      EMBEDDING_PROVIDER: "openai",
      EMBEDDING_MODEL: "text-embedding-3-small",
      EMBEDDING_DIMENSION: "768",
      EMBEDDING_BATCH_SIZE: "64",
    },
  },
  anthropic: {
    label: "Anthropic / Voyage — coming in v0.3",
    available: false,
  },
  qwen: {
    label: "Qwen / open-source local — coming in v0.3",
    available: false,
  },
};

/**
 * Generate a .env file for docker compose.
 * `apiKeys` is an object like { GEMINI_API_KEY: "..." }; only included for
 * API-backed profiles.
 */
export async function writeEnv({ embeddingChoice, apiKeys = {} }) {
  const secrets = {
    serverSecret: randomHex(32),
    systemPassword: randomHex(16),
    postgresPassword: randomHex(16),
  };

  const profile = EMBEDDING_PROFILES[embeddingChoice];
  if (!profile || !profile.available) {
    throw new Error(`Embedding profile ${embeddingChoice} is not available.`);
  }

  const lines = [
    "# Generated by @synsci/delphi installer.",
    "# Do not check this file into version control.",
    "",
    `SERVER_SECRET=${secrets.serverSecret}`,
    `SYSTEM_PASSWORD=${secrets.systemPassword}`,
    "",
    `POSTGRES_USER=synsc`,
    `POSTGRES_PASSWORD=${secrets.postgresPassword}`,
    `POSTGRES_DB=synsc`,
    `DATABASE_URL=postgresql://synsc:${secrets.postgresPassword}@postgres:5432/synsc`,
    "",
    `SYNSC_API_HOST=0.0.0.0`,
    `SYNSC_API_PORT=8742`,
    `SYNSC_REQUIRE_AUTH=true`,
    `FRONTEND_URL=http://localhost:3000`,
    "",
    "# Embeddings",
    ...Object.entries(profile.env).map(([k, v]) => `${k}=${v}`),
    "",
    "# Provider API keys (only the selected one needs to be set)",
    ...Object.entries(apiKeys).map(([k, v]) => `${k}=${v}`),
    "",
  ];

  await fs.writeFile(ENV_FILE, lines.join("\n"), { mode: 0o600 });
  return secrets;
}

export async function saveState(state) {
  await fs.mkdir(ROOT, { recursive: true });
  await fs.writeFile(STATE_FILE, JSON.stringify(state, null, 2), { mode: 0o600 });
}

export async function loadState() {
  try {
    const raw = await fs.readFile(STATE_FILE, "utf8");
    return JSON.parse(raw);
  } catch {
    return null;
  }
}
