import fs from "node:fs/promises";
import crypto from "node:crypto";
import { ENV_FILE, STATE_FILE, ROOT } from "./paths.js";

function randomHex(bytes) {
  return crypto.randomBytes(bytes).toString("hex");
}

/**
 * Embedding profiles. Each maps to env vars consumed by the backend.
 *
 *   kind: "local"  — sentence-transformers in-process. The model is pulled
 *                    from the HuggingFace Hub at first boot, then runs on
 *                    CPU/GPU inside the api container. HF_TOKEN is only
 *                    needed for gated models or higher Hub download rates.
 *   kind: "api"    — Gemini / OpenAI hosted embeddings; needs an API key.
 *
 * Backends targeting >768-dim outputs (Gemini, OpenAI) truncate at request
 * time. Local sentence-transformers does not truncate — pick a 768-dim
 * model (jina-v2-base-code, bge-base, mpnet) or set EMBEDDING_DIMENSION
 * yourself if you've migrated the pgvector schema.
 *
 * The HuggingFace Inference API (kind: "huggingface" in the backend) is
 * intentionally not exposed here — most users want the in-process path.
 * Power users can opt in by editing .env after install.
 */
export const EMBEDDING_PROFILES = {
  local_balanced: {
    label: "Local — sentence-transformers (any HuggingFace model, runs in-process, no API call)",
    kind: "local",
    available: true,
    promptModel: true,
    defaultModel: "jinaai/jina-embeddings-v2-base-code",
    modelHint: "any HF model id; pick a 768-dim one (jinaai/jina-embeddings-v2-base-code, BAAI/bge-base-en-v1.5, sentence-transformers/all-mpnet-base-v2)",
    optionalKeyEnvVar: "HF_TOKEN",
    optionalKeyHint: "https://huggingface.co/settings/tokens",
    optionalKeyReason: "only needed for gated/private models or higher Hub download rate limits",
    env: {
      EMBEDDING_PROVIDER: "local",
      EMBEDDING_DIMENSION: "768",
      EMBEDDING_DEVICE: "auto",
      EMBEDDING_BATCH_SIZE: "64",
    },
  },
  gemini: {
    label: "Google Gemini — gemini-embedding-001 (hosted, requires API key)",
    kind: "api",
    available: true,
    keyEnvVar: "GEMINI_API_KEY",
    keyHint: "https://aistudio.google.com/apikey",
    env: {
      EMBEDDING_PROVIDER: "gemini",
      EMBEDDING_MODEL: "gemini-embedding-001",
      EMBEDDING_DIMENSION: "768",
      EMBEDDING_BATCH_SIZE: "32",
    },
  },
  openai: {
    label: "OpenAI — text-embedding-3-small (hosted, requires API key)",
    kind: "api",
    available: true,
    keyEnvVar: "OPENAI_API_KEY",
    keyHint: "https://platform.openai.com/api-keys",
    env: {
      EMBEDDING_PROVIDER: "openai",
      EMBEDDING_MODEL: "text-embedding-3-small",
      EMBEDDING_DIMENSION: "768",
      EMBEDDING_BATCH_SIZE: "64",
    },
  },
};

/**
 * Generate a .env file for docker compose.
 *
 * @param {object} opts
 * @param {string} opts.embeddingChoice         — key in EMBEDDING_PROFILES
 * @param {object} [opts.providerConfig]        — extra env from prompts
 *   (API key, model name overrides). Keys here win over `profile.env`,
 *   so a user-typed EMBEDDING_MODEL replaces the profile default.
 * @param {string} [opts.systemPassword]        — user-chosen dashboard
 *   password. Falls back to a random 16-byte hex when omitted.
 */
export async function writeEnv({ embeddingChoice, providerConfig = {}, systemPassword }) {
  const secrets = {
    serverSecret: randomHex(32),
    systemPassword: systemPassword || randomHex(16),
    postgresPassword: randomHex(16),
  };

  const profile = EMBEDDING_PROFILES[embeddingChoice];
  if (!profile || !profile.available) {
    throw new Error(`Embedding profile ${embeddingChoice} is not available.`);
  }

  const merged = { ...profile.env, ...providerConfig };

  const lines = [
    "# Generated by @synsci/delphi installer.",
    "# Do not check this file into version control.",
    "",
    `SERVER_SECRET=${secrets.serverSecret}`,
    `SYSTEM_PASSWORD=${secrets.systemPassword}`,
    "",
    `POSTGRES_USER=synsc`,
    `POSTGRES_PASSWORD=${secrets.postgresPassword}`,
    `POSTGRES_DB=synsc`,
    `DATABASE_URL=postgresql://synsc:${secrets.postgresPassword}@postgres:5432/synsc`,
    "",
    `SYNSC_API_HOST=0.0.0.0`,
    `SYNSC_API_PORT=8742`,
    `SYNSC_REQUIRE_AUTH=true`,
    `FRONTEND_URL=http://localhost:3000`,
    "",
    "# Embeddings (provider config + any user-supplied API keys / model)",
    ...Object.entries(merged).map(([k, v]) => `${k}=${v}`),
    "",
  ];

  await fs.writeFile(ENV_FILE, lines.join("\n"), { mode: 0o600 });
  return secrets;
}

export async function saveState(state) {
  await fs.mkdir(ROOT, { recursive: true });
  await fs.writeFile(STATE_FILE, JSON.stringify(state, null, 2), { mode: 0o600 });
}

export async function loadState() {
  try {
    const raw = await fs.readFile(STATE_FILE, "utf8");
    return JSON.parse(raw);
  } catch {
    return null;
  }
}
